Securing the obfuscated password file/folder
iBridges-for-iRODS/iBridges-GUI pull request #282
Opened 2024-11-07 13:55 UTC by joergsteinkamp

Dear all,
Nice and usefull tool. The obfuscated password needs a better protection in my opinion. I inserted two possibilities, how to create either a folder with permission (700) or a file with (600). Nevertheless, I don't know how this would translate inti the Windows world. See also Stackoverflow where I got the code snippet from:
https://stackoverflow.com/questions/36745577/how-do-you-create-in-python-a-file-with-permissions-other-users-can-write
Kind regards,
Jörg

2024-11-07 15:02 UTC, chStaiger commented
Thank you for the code contribution, it is. indeed very useful. We will test whether it will also work in our windows environments. And we will also adjust the iBridges CLI in our API package accordingly.

2024-11-07 15:05 UTC, chStaiger commented
@joergsteinkamp  I started our linting and it finds some python errors. E.g. the `os` module is not imported etc. Could you have a look at this please?

2024-11-08 10:34 UTC, chStaiger commented
Thanks for the update. Unfortunately the linters are still complaining.
You can check it yourself locally with 

```
ruff ibridgesgui
pylint ibridgesgui
```

2024-11-08 10:48 UTC, joergsteinkamp commented
Sorry, I missed inserting the 'import os' in login.py in my github repo. It's now in there. Also the docstring in imperative: 'Creates' and 'Creating' was not accepted.

2024-11-08 11:06 UTC, chStaiger commented on ibridgesgui/login.py
> +def strictwrite(path, flags, mode='0o600'):
```suggestion

def strictwrite(path, flags, mode='0o600'):
```

2024-11-08 11:10 UTC, qubixes approved these changes

2024-11-08 11:13 UTC, chStaiger commented
Thank you for the update. I tested your new feature on Mac, but I run into an error:

```
ERROR:ibridges-gui:Failed to login: TypeError("'str' object cannot be interpreted as an integer")
Traceback (most recent call last):
  File "/Users/user/test-git/iBridges-GUI/ibridgesgui/login.py", line 113, in login_function
    with open(IRODSA, "w",  encoding="utf-8", opener=strictwrite) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/test-git/iBridges-GUI/ibridgesgui/login.py", line 29, in strictwrite
    return os.open(path, flags, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer
```

2024-11-08 11:15 UTC, chStaiger commented
Thanks for the update. I tried the new feature on Mac but I run into this error:

```
ERROR:ibridges-gui:Failed to login: TypeError("'str' object cannot be interpreted as an integer")
Traceback (most recent call last):
  File "/Users/user/test-git/iBridges-GUI/ibridgesgui/login.py", line 113, in login_function
    with open(IRODSA, "w",  encoding="utf-8", opener=strictwrite) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/test-git/iBridges-GUI/ibridgesgui/login.py", line 29, in strictwrite
    return os.open(path, flags, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer
```

It might also be nice to have a unit test for this function. Would you like to write that test or would you like us to do it?

2024-11-08 11:21 UTC, chStaiger commented on ibridgesgui/login.py
> +def strictwrite(path, flags, mode='0o600'):
```suggestion
def strictwrite(path, flags, mode=600):
```

2024-11-08 11:23 UTC, chStaiger requested changes
Something seems to be wrong with the mode flag in `os.open`:

```
In [4]: ?os.open
Signature: os.open(path, flags, mode=511, *, dir_fd=None)
Docstring:
Open a file for low level IO.  Returns a file descriptor (integer).
```

2024-11-08 12:06 UTC, joergsteinkamp commented
Ok, on Linux I had trouble with integers looking like permissions, the mode was more readable for me in the octal version. 511 is 0o777 in octal, which is the default and would give the default as access rights. 0o600 would be 384 and 0o700 448, respectiively. Use print(0o700) to convert it to integers and oct(511) vice versa.

2024-11-08 15:43 UTC, chStaiger commented on ibridgesgui/login.py
> +def strictwrite(path, flags, mode='0o600'):
```suggestion
def strictwrite(path, flags, mode=0o600):
```

2024-11-08 15:44 UTC, chStaiger approved these changes
Thanks for this very useful and nice contribution!

2024-11-08 15:46 UTC, merged